name: ubuntu-frame-vnc
base: core24
summary: A VNC server for Ubuntu Frame
description: |
  This allows for remote access to a running Ubuntu Frame instance.

  Upon install on Ubuntu Core, it will serve VNC on `localhost:5900`.

  See [the Ubuntu Frame documentation](https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame) for more information.

grade: stable
confinement: strict
adopt-info: wayvnc

environment:
  LD_LIBRARY_PATH:
    "${SNAP}/usr/local/lib\
     :${SNAP}/usr/local/lib/${CRAFT_ARCH_TRIPLET}\
     :${SNAP_LIBRARY_PATH}\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/blas\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/lapack"
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
    - bin/run-daemon
    - bin/wayland-launch
    - bin/gpu-2404-wrapper
    command: bin/ubuntu-frame-vnc

  ubuntu-frame-vnc:
    command-chain:
    - bin/wayland-launch
    - bin/gpu-2404-wrapper
    command: bin/ubuntu-frame-vnc.user

plugs:
  wayland:
  network-bind:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  opengl:

parts:
  scripts:
    plugin: dump
    source: scripts
    stage-packages:
    - inotify-tools

  wayvnc:
    plugin: nil
    stage-packages:
    - libavcodec60
    - libjansson4
    - libpam0g
    - libpixman-1-0
    - libx264-164
    - wayvnc
    override-stage: |
      craftctl default
      recipe_version=`git -C ${CRAFT_PROJECT_DIR} rev-list --count HEAD`
      craftctl set version=${recipe_version}-wayvnc$( dpkg-parsechangelog --file ${CRAFT_PART_INSTALL}/usr/share/doc/wayvnc/changelog* --show-field Version )

  gpu-snap:
    after: [scripts, wayvnc]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
