name: ubuntu-frame-vnc
base: core26
summary: A VNC server for Ubuntu Frame
description: |
  This allows for remote access to a running Ubuntu Frame instance.

  Upon install on Ubuntu Core, it will serve VNC on `localhost:5900`.

  See [the Ubuntu Frame documentation](https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame) for more information.

grade: stable
confinement: strict
adopt-info: wayvnc

environment:
  LD_LIBRARY_PATH:
    "${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}\
     :${SNAP_LIBRARY_PATH}\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack"
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
    - bin/run-daemon
    - bin/wayland-launch
    - bin/gpu-2604-wrapper
    command: bin/ubuntu-frame-vnc
    plugs: &plugs
    - wayland
    - network-bind
    - opengl

  ubuntu-frame-vnc:
    command-chain:
    - bin/wayland-launch
    - bin/gpu-2604-wrapper
    command: bin/ubuntu-frame-vnc.user
    plugs: *plugs

plugs:
  gpu-2604:
    interface: content
    target: $SNAP/gpu-2604
    default-provider: mesa-2604

parts:
  scripts:
    plugin: dump
    source: scripts
    stage-packages:
    - inotify-tools

  wayvnc:
    plugin: nil
    override-build: |
      craftctl default
      craftctl set version=$(
        dpkg-parsechangelog \
          --file ${CRAFT_PART_INSTALL}/usr/share/doc/wayvnc/changelog* \
          --show-field Version \
        | sed -rne 's/(^[0-9.]+).*/\1/p'
      )-snap$( git -C $CRAFT_PROJECT_DIR rev-list --count HEAD )
    stage-packages:
    - wayvnc

  gpu-snap:
    after: [scripts, wayvnc]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2604-cleanup mesa-2604
    prime:
      - bin/gpu-2604-wrapper
