name: ubuntu-frame-vnc
base: core22
version: git
summary: A VNC server for Ubuntu Frame
description: |
  This allows for remote access to a running Ubuntu Frame instance.

  Upon install on Ubuntu Core, it will serve VNC on `localhost:5900`.

  See [the Ubuntu Frame documentation](https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame) for more information.

grade: stable
confinement: strict

environment:
  LD_LIBRARY_PATH:
    "${SNAP}/usr/local/lib\
     :${SNAP}/usr/local/lib/${CRAFT_ARCH_TRIPLET}\
     :${SNAP_LIBRARY_PATH}\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/blas\
     :${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/lapack"
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
    - bin/run-daemon
    - bin/wayland-launch
    - bin/graphics-core22-wrapper
    command: bin/ubuntu-frame-vnc

  ubuntu-frame-vnc:
    command-chain:
    - bin/wayland-launch
    - bin/graphics-core22-wrapper
    command: bin/ubuntu-frame-vnc

plugs:
  wayland:
  network-bind:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22
  opengl:

parts:
  scripts:
    plugin: dump
    source: scripts
    stage-packages:
    - inotify-tools

  ffmpeg:
    source: https://git.ffmpeg.org/ffmpeg.git
    source-tag: n5.1.2
    source-depth: 1
    build-packages:
    - libdrm-dev
    - libx264-dev
    - libva-dev
    - nasm
    plugin: autotools
    autotools-configure-parameters:
    - --enable-gpl
    - --disable-programs
    - --disable-doc
    - --disable-static
    - --enable-shared
    - --disable-avdevice
    - --disable-avformat
    - --disable-postproc
    - --disable-swresample
    - --disable-swscale
    - --disable-everything
    - --disable-iconv
    - --disable-libxcb
    - --disable-zlib
    - --enable-libx264
    - --enable-encoder=libx264
    - --enable-libdrm
    - --enable-vaapi
    override-build: |
      snapcraftctl build
      sed -i 's@libdir=/usr/local/@libdir=${prefix}/@' ${CRAFT_PART_INSTALL}/usr/local/lib/pkgconfig/libavcodec.pc
      sed -i 's@libdir=/usr/local/@libdir=${prefix}/@' ${CRAFT_PART_INSTALL}/usr/local/lib/pkgconfig/libavfilter.pc
      sed -i 's@libdir=/usr/local/@libdir=${prefix}/@' ${CRAFT_PART_INSTALL}/usr/local/lib/pkgconfig/libavutil.pc
      sed -i 's@includedir=/usr/local/@includedir=${prefix}/@' ${CRAFT_PART_INSTALL}/usr/local/lib/pkgconfig/libavcodec.pc
      sed -i 's@includedir=/usr/local/@includedir=${prefix}/@' ${CRAFT_PART_INSTALL}/usr/local/lib/pkgconfig/libavfilter.pc
      sed -i 's@includedir=/usr/local/@includedir=${prefix}/@' ${CRAFT_PART_INSTALL}/usr/local/lib/pkgconfig/libavutil.pc
    stage-packages:
    - libx264-163
    - libva-drm2
    - libva2

  aml:
    plugin: nil
    source: https://github.com/any1/aml.git
    source-tag: v0.3.0
    source-depth: 1

  neatvnc:
    after: [ffmpeg]
    plugin: nil
    source: https://github.com/any1/neatvnc.git
    source-tag: v0.6.0
    source-depth: 1
    build-packages:
    - gnutls-dev
    - libdrm-dev
    - libgbm-dev
    - libturbojpeg0-dev
    - zlib1g-dev
    stage-packages:
    - libgbm1
    - libgnutls30
    - libturbojpeg
    - zlib1g

  xkbcommon:
    source: https://github.com/xkbcommon/libxkbcommon.git
    source-tag: xkbcommon-1.5.0
    source-depth: 1
    build-packages:
    - bison
    - libxcb-xkb-dev
    - libxml2-dev
    - wayland-protocols
    stage-packages:
    - xkb-data
    - libxcb-xkb1
    - libxml2
    plugin: meson
    meson-parameters:
    - -Denable-docs=false

  wayvnc:
    after: [ffmpeg, xkbcommon, aml, neatvnc]
    source: https://github.com/any1/wayvnc.git
    source-tag: v0.6.2
    override-pull: |
      snapcraftctl pull
      mkdir subprojects
      ln -s ../../../aml/src subprojects/aml
      ln -s ../../../neatvnc/src subprojects/neatvnc
    build-packages:
    - libavcodec-dev
    - libdrm-dev
    - libgbm-dev
    - libjansson-dev
    - libpam0g-dev
    - libpixman-1-dev
    - libwayland-dev
    - meson
    - pkg-config
    plugin: meson
    meson-parameters:
    - -Dscreencopy-dmabuf=enabled
    - -Dneatvnc:h264=enabled
    stage-packages:
    - libavcodec58
    - libgbm1
    - libjansson4
    - libpam0g
    - libpixman-1-0
    - libwayland-client0

  graphics-core22:
    after: [scripts, aml, ffmpeg, xkbcommon, neatvnc, wayvnc]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22
    prime:
      - bin/graphics-core22-wrapper
