#!/bin/sh
set -eux

# we install with the daemon disabled, the configure hook
# will start and enable it if appropriate
snapctl stop --disable "$SNAP_INSTANCE_NAME.daemon"

daemon=$(snapctl get daemon)
if [ "$daemon" = "" ]
then
  # if no model at all, it's either classic or something is wrong
  if ! snapctl model > /dev/null || [ "$( snapctl model | awk '/^classic:/ { print $2 }' )" = "true" ]
  then snapctl set daemon=false
  else snapctl set daemon=true
  fi
fi
